version: '3.8'

services:
  # Aplicação Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      # Usando a string de conexão para o banco de dados externo
      - DATABASE_URL=postgresql://postgres:masterkey@50.114.32.196:5432/imobiliaria_db?schema=public
      # Definindo um valor padrão para JWT_SECRET
      - JWT_SECRET=chave_jwt_secreta_para_desenvolvimento_local_12345
      - UPLOAD_DIR=./public/uploads
      - PORT=4000
      - HOSTNAME=0.0.0.0
      # URL base para o EasyPanel (substitua pelo seu domínio configurado no EasyPanel)
      - NEXT_PUBLIC_BASE_URL=https://seu-dominio-configurado-no-easypanel
    volumes:
      - uploads:/app/public/uploads
    restart: unless-stopped
    networks:
      - app-network

# Volume para persistência de uploads
volumes:
  uploads:
    driver: local

# Rede para a aplicação
networks:
  app-network:
    driver: bridge