version: '3.8'

services:
  # Aplicação Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - UPLOAD_DIR=./public/uploads
      - PORT=4000
      - HOSTNAME=0.0.0.0
    volumes:
      - uploads:/app/public/uploads
    restart: unless-stopped
    networks:
      - app-network

# Volume para persistência de uploads
volumes:
  uploads:
    driver: local

# Rede para a aplicação
networks:
  app-network:
    driver: bridge